Parameters:
  RoleTempName:
    Description: Name of the base stack with all infra resources
    Type: String
    Default: cicds3role
  MyIP:
    Type: String
  KeyName:
    Type: String
  InstanceType:
    Type: String
    Default: t3.small

Mappings:
  AmiRegionMap:
    me-south-1:
      AMI: "ami-03925b32489532bc2"
    ap-south-1:
      AMI: "ami-0f8ca728008ff5af4"
    us-west-1:
      AMI: "ami-0e4035ae3f70c400f"
    eu-west-1:
      AMI: "ami-0bb3fad3c0286ebd5"

Resources:
  JenkinsInst:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !FindInMap
        - AmiRegionMap
        - !Ref AWS::Region
        - AMI
      Tags:
        - Key: "Name"
          Value: !Join
            - ""
            - - "Jenkins in "
              - !Ref AWS::Region
      SecurityGroups:
        - !Ref JenkinsSG
      IamInstanceProfile:
        Fn::ImportValue:
          Fn::Sub: "${RoleTempName}-VPS3RoleProfileName"
      UserData:
        Fn::Base64:                                # YAML makes userdata much cleaner
          !Sub |
          #!/bin/bash
          sleep 60
          sudo apt update
          sudo apt install openjdk-8-jdk -y
          sudo apt install maven git wget unzip -y
          sudo apt install awscli -y
          curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
          echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
          sudo apt-get update
          sudo apt-get install jenkins -y
          sleep 10
          systemctl stop jenkins
          sleep 10
          aws s3 cp s3://suheb-vpapp/jenkins_cicdjobs.tar.gz /var/lib/
          cd /var/lib/
          tar xzvf jenkins_cicdjobs.tar.gz
          chown jenkins.jenkins /var/lib/jenkins -R
          systemctl start jenkins
  JenkinsSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: JenkinsSG
      GroupDescription: Allow SSH & HTTP from myip
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: !Ref MyIP

        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0

Outputs:
  MyEC2InstancePublicIP:
    Value: !GetAtt JenkinsInst.PublicIp
  MyEC2InstancePrivateIP:
    Value: !GetAtt JenkinsInst.PrivateIp
  MyEC2InstanceID:
    Value: !Ref JenkinsInst
  JenkSecurityGroupId:
    Description: Security Group 1 ID
    Value:
      Fn::GetAtt:
        - JenkinsSG
        - GroupId
    Export:
      Name: jenk-SGID